<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" tests="11" skipped="0" failures="0" errors="0" timestamp="2021-05-18T08:52:26" hostname="LAPTOP-170P7NSC" time="0.286">
  <properties/>
  <testcase name="modifyByNameIfPersonNotFound()" classname="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" time="0.222"/>
  <testcase name="delete()" classname="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" time="0.016"/>
  <testcase name="modify()" classname="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" time="0.005"/>
  <testcase name="modifyByName()" classname="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" time="0.004"/>
  <testcase name="getPersonIfNotFound()" classname="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" time="0.002"/>
  <testcase name="put()" classname="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" time="0.002"/>
  <testcase name="modifyIfNameIsDifferent()" classname="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" time="0.006"/>
  <testcase name="modifyIfPersonNotFound()" classname="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" time="0.006"/>
  <testcase name="getPerson()" classname="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" time="0.003"/>
  <testcase name="deleteIfPersonNotFound()" classname="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" time="0.008"/>
  <testcase name="getPeopleByName()" classname="com.fastcampus.javaallinone.project3.demo.Service.PersonServiceTest" time="0.004"/>
  <system-out><![CDATA[2021-05-18 17:52:26.852 ERROR 16060 --- [    Test worker] c.f.j.p.d.E.PersonNotFoundException      : Person Entity does not exist
2021-05-18 17:52:26.894 ERROR 16060 --- [    Test worker] c.f.j.p.d.E.RenameNotPermittedException  : Rename not permitted
2021-05-18 17:52:26.902 ERROR 16060 --- [    Test worker] c.f.j.p.d.E.PersonNotFoundException      : Person Entity does not exist
2021-05-18 17:52:26.914 ERROR 16060 --- [    Test worker] c.f.j.p.d.E.PersonNotFoundException      : Person Entity does not exist
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
